# NOTEBOOK SETTINGS
# [notebook]
# dir = "~/notebook"

# NOTE SETTINGS
[note]

# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "ja"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
filename = "{{id}}-{{slug title}}"

# The file extension used for the notes.
extension = "md"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

# The charset used for random IDs.
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 4

# Letter case for the random IDs.
id-case = "lower"


# EXTRA VARIABLES
[extra]
author = "Koei KAJI"

# GROUP OVERRIDES
[group.standup]
paths = ["Standup"]

[group.standup.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "standup.md"

[group.daily]
paths = ["Journal/Daily"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[group.fleeting]
paths = ["FleetingNotes"]

[group.fleeting.note]
filename = "{{id}}-{{format-date now 'timestamp'}}"
extension = "md"

[group.permanent]
paths = ["PermanentNotes"]

[group.permanent.note]
filename = "{{id}}-{{format-date now 'timestamp'}}"
extension = "md"

[group.structure]
paths = ["StructureNotes"]

[group.structure.note]
filename = "{{slug title}}"
extension = "md"

[group.literature]
paths = ["LiteratureNotes"]

[group.literature.note]
filename = "{{id}}-{{format-date now 'timestamp'}}"
extension = "md"
template = "literature.md"

[group.english]
paths = ["EnglishStudy/Topic"]

[group.english.note]
filename = "{{id}}-{{format-date now 'timestamp'}}"
extension = "md"
template = "english_topic.md"

# MARKDOWN SETTINGS
[format.markdown]
# Format used to generate links between notes.
# Either "wiki", "markdown" or a custom template. Default is "markdown".
link-format = "wiki"
# Indicates whether a link's path will be percent-encoded.
# Defaults to true for "markdown" format and false for "wiki" format.
link-encode-path = false
# Indicates whether a link's path file extension will be removed.
# Defaults to true.
#link-drop-extension = true

# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true

# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Default shell used by aliases and commands.
shell = "/bin/zsh"

# Pager used to scroll through long output.
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]

config = "nvim ~/.config/zk/config.toml"

# Make directories
mkdir = """
mkdir -p $ZK_NOTEBOOK_DIR/Standup \
&& mkdir -p $ZK_NOTEBOOK_DIR/Journal/Daily \
&& mkdir -p $ZK_NOTEBOOK_DIR/FleetingNotes \
&& mkdir -p $ZK_NOTEBOOK_DIR/PermanentNotes \
&& mkdir -p $ZK_NOTEBOOK_DIR/StructureNotes \
&& mkdir -p $ZK_NOTEBOOK_DIR/LiteratureNotes \
&& mkdir -p $ZK_NOTEBOOK_DIR/EnglishStudy/Topic
"""


# Edit the last modified note.
edlast = "zk edit --limit 1 --sort modified- $@"

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Show a random note.
lucky = "zk list --quiet --format full --sort random --limit 1"

ls = "zk edit --interactive"
rm = "zk list --interactive --quiet --format path --delimiter0 --sort word-count $@ | xargs -0 rm -v --"
update = "cd $ZK_NOTEBOOK_DIR; git add -A; git commit -am 'updating'; git push; cd -"
tagless = "zk edit --interactive --tagless"

flt = 'zk new --no-input "$ZK_NOTEBOOK_DIR/FleetingNotes" --title "$*"'
str = 'zk new --no-input "$ZK_NOTEBOOK_DIR/StructureNotes" --title "$*"'
perm = 'zk new --no-input "$ZK_NOTEBOOK_DIR/PermanentNotes" --title "$*"'
lit= 'zk new --no-input "$ZK_NOTEBOOK_DIR/LiteratureNotes" --title "$*"'
eng= 'zk new --no-input "$ZK_NOTEBOOK_DIR/EnglishStudy/Topic"'
ls-flt = "zk edit $ZK_NOTEBOOK_DIR/FleetingNotes --sort created- --interactive"
ls-str = "zk edit $ZK_NOTEBOOK_DIR/StructureNotes --sort created- --interactive"
ls-perm = "zk edit $ZK_NOTEBOOK_DIR/PermanentNotes --sort created- --interactive"
ls-lit = "zk edit $ZK_NOTEBOOK_DIR/LiteratureNotes --sort created- --interactive"
ls-eng = "zk edit $ZK_NOTEBOOK_DIR/EnglishStudy/Topic --sort created- --interactive"
cit = 'zk list --interactive --quiet --format path --delimiter0 "$ZK_NOTEBOOK_DIR/LiteratureNotes" | xargs -0 yq --front-matter=extract -r "(.authors | join(\",\")) + \". \" + (.title) + \". \" + (.publication) + \". \" + (.published_at) + \". \" + (.url)" | pbcopy'

daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/Journal/Daily"'
standup = 'zk new --no-input "$ZK_NOTEBOOK_DIR/Standup"'


# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
