require("catppuccin").setup({
  flavor = "mocha",
  transparent_background = true,
  term_colors = true,
  integrations = {
    aerial = true,
    barbar = true,
    cmp = true,
    diffview = true,
    fzf = true,
    gitsigns = true,
    harpoon = true,
    markdown = true,
    mason = true,
    mini = {
      enabled = true,
      indentscope_color = "",
    },
    neotree = true,
    -- neotest = true,
    -- dap = true,
    -- dap-ui = true,
    notify = true,
    nvim_surround = true,
    nvimtree = true,
    treesitter_context = true,
    treesitter = true,
    ufo = true,
    render_markdown = true,
    telescope = {
      enabled = true,
    },
    which_key = true,
  },
})
