-- require("tokyonight").setup({
--   style = "night",
--   light_style = "night",
--   transparent = true,
--   styles = {
--     sidebars = "transparent",
--     floats = "transparent",
--   },
-- })
